# Generated by Django 4.2.3 on 2023-08-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('period', models.TextField()),
                ('description', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
