# Generated by Django 4.2.3 on 2023-08-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Financeapp',
        ),
    ]
