# Generated by Django 4.2.3 on 2023-08-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_rename_resume_financeapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financeapp',
            new_name='Resume',
        ),
    ]
