# Generated by Django 4.2.3 on 2023-08-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_rename_financeapp_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
